/**
 * Deepgram streaming STT `language` query values for model `nova-3`.
 * Source: Deepgram "Models & Languages Overview" — Nova-3 row
 * https://developers.deepgram.com/docs/models-languages-overview
 *
 * BCP-47 tags are passed through to the listen WebSocket unchanged.
 */
export const DEFAULT_DEEPGRAM_STT_LANGUAGE = 'en'

export interface DeepgramSttLanguageOption {
  code: string
  label: string
}

/** Curated display order: English default, multilingual, then A–Z by label. */
export const DEEPGRAM_NOVA3_STT_LANGUAGES: readonly DeepgramSttLanguageOption[] = [
  { code: 'en', label: 'English' },
  { code: 'en-US', label: 'English (United States)' },
  { code: 'en-AU', label: 'English (Australia)' },
  { code: 'en-GB', label: 'English (United Kingdom)' },
  { code: 'en-IN', label: 'English (India)' },
  { code: 'en-NZ', label: 'English (New Zealand)' },
  { code: 'multi', label: 'Multilingual (mixed languages)' },
  { code: 'ar', label: 'Arabic' },
  { code: 'ar-AE', label: 'Arabic (United Arab Emirates)' },
  { code: 'ar-DZ', label: 'Arabic (Algeria)' },
  { code: 'ar-EG', label: 'Arabic (Egypt)' },
  { code: 'ar-IQ', label: 'Arabic (Iraq)' },
  { code: 'ar-IR', label: 'Arabic (Iran)' },
  { code: 'ar-JO', label: 'Arabic (Jordan)' },
  { code: 'ar-KW', label: 'Arabic (Kuwait)' },
  { code: 'ar-LB', label: 'Arabic (Lebanon)' },
  { code: 'ar-MA', label: 'Arabic (Morocco)' },
  { code: 'ar-PS', label: 'Arabic (Palestine)' },
  { code: 'ar-QA', label: 'Arabic (Qatar)' },
  { code: 'ar-SA', label: 'Arabic (Saudi Arabia)' },
  { code: 'ar-SD', label: 'Arabic (Sudan)' },
  { code: 'ar-SY', label: 'Arabic (Syria)' },
  { code: 'ar-TD', label: 'Arabic (Chad)' },
  { code: 'ar-TN', label: 'Arabic (Tunisia)' },
  { code: 'be', label: 'Belarusian' },
  { code: 'bn', label: 'Bengali' },
  { code: 'bs', label: 'Bosnian' },
  { code: 'bg', label: 'Bulgarian' },
  { code: 'ca', label: 'Catalan' },
  { code: 'zh', label: 'Chinese (Mandarin, Simplified)' },
  { code: 'zh-CN', label: 'Chinese (Mandarin, Simplified, China)' },
  { code: 'zh-Hans', label: 'Chinese (Simplified, Hans)' },
  { code: 'zh-HK', label: 'Chinese (Cantonese, Hong Kong)' },
  { code: 'zh-TW', label: 'Chinese (Mandarin, Taiwan)' },
  { code: 'zh-Hant', label: 'Chinese (Traditional, Hant)' },
  { code: 'hr', label: 'Croatian' },
  { code: 'cs', label: 'Czech' },
  { code: 'da', label: 'Danish' },
  { code: 'da-DK', label: 'Danish (Denmark)' },
  { code: 'nl', label: 'Dutch' },
  { code: 'nl-BE', label: 'Flemish (Belgium)' },
  { code: 'et', label: 'Estonian' },
  { code: 'fi', label: 'Finnish' },
  { code: 'fr', label: 'French' },
  { code: 'fr-CA', label: 'French (Canada)' },
  { code: 'de', label: 'German' },
  { code: 'de-CH', label: 'German (Switzerland)' },
  { code: 'el', label: 'Greek' },
  { code: 'he', label: 'Hebrew' },
  { code: 'hi', label: 'Hindi' },
  { code: 'hu', label: 'Hungarian' },
  { code: 'id', label: 'Indonesian' },
  { code: 'it', label: 'Italian' },
  { code: 'ja', label: 'Japanese' },
  { code: 'kn', label: 'Kannada' },
  { code: 'ko', label: 'Korean' },
  { code: 'ko-KR', label: 'Korean (South Korea)' },
  { code: 'lv', label: 'Latvian' },
  { code: 'lt', label: 'Lithuanian' },
  { code: 'mk', label: 'Macedonian' },
  { code: 'ms', label: 'Malay' },
  { code: 'mr', label: 'Marathi' },
  { code: 'no', label: 'Norwegian' },
  { code: 'fa', label: 'Persian' },
  { code: 'pl', label: 'Polish' },
  { code: 'pt', label: 'Portuguese' },
  { code: 'pt-BR', label: 'Portuguese (Brazil)' },
  { code: 'pt-PT', label: 'Portuguese (Portugal)' },
  { code: 'ro', label: 'Romanian' },
  { code: 'ru', label: 'Russian' },
  { code: 'sr', label: 'Serbian' },
  { code: 'sk', label: 'Slovak' },
  { code: 'sl', label: 'Slovenian' },
  { code: 'es', label: 'Spanish' },
  { code: 'es-419', label: 'Spanish (Latin America)' },
  { code: 'sv', label: 'Swedish' },
  { code: 'sv-SE', label: 'Swedish (Sweden)' },
  { code: 'tl', label: 'Tagalog' },
  { code: 'ta', label: 'Tamil' },
  { code: 'te', label: 'Telugu' },
  { code: 'th', label: 'Thai' },
  { code: 'th-TH', label: 'Thai (Thailand)' },
  { code: 'tr', label: 'Turkish' },
  { code: 'uk', label: 'Ukrainian' },
  { code: 'ur', label: 'Urdu' },
  { code: 'vi', label: 'Vietnamese' },
]
